name = "DoubleWellPkg"
uuid = "65d67d9b-4f51-4c99-bae6-31dd0cff4319"
authors = ["Daniel Pals <Daniel.Pals@tum.de>"]
version = "1.0.0-DEV"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
